### ISSUE TITLE
[Question] Uploading file itself rather than giving full path

### ISSUE THREAD

**Issue by SerdaOzun** [Backblaze/b2-sdk-python#151]
Hello,
I've read quite a bit through the documentation, but haven't really found an answer. 

Users are uploading their  files to the website (Using flask) and I'd like to upload these files backblaze b2. I have a [FileStorage Object](https://tedboy.github.io/flask/generated/generated/werkzeug.FileStorage.html#werkzeug-filestorage) which I'd rather not save to my disk locally and afterwards upload to backblaze as it creates an unnecessary step.

The way I see it there is 'upload_local_file' and 'upload'.
The first requires the full path to the file, which I don't have and the second one [upload](https://b2-sdk-python.readthedocs.io/en/master/api/bucket.html#b2sdk.v1.Bucket.upload) I don't quite understand how to use it or what upload_source is supposed to be.

Can I achieve what I want or does the API not support uploading files directly?

**Edit**: easier question while I work around this issue: How to get the generated Id when I upload a file with upload_local_file?

Thanks

**Comment by ppolewicz** [comment]
upload methods return a FileVersion object, i think, and file ID is inside of it.

As for your original question, you can Use an in-memory file as a source, it requires you to get all the data from the user and buffer it before you start sending it. The reason is that b2sdk may need to restart the upload if something goes wrong (with the network, usually), that's why the file can't really be streamed straight through into the cloud.

Theoretically it could be possible to support an upload that cannot retry and will break off in case of a failure, but that could only really work for small files (less than 5GB).

Will buffering the file in memory for the duration of the upload be ok for you?

**Comment by SerdaOzun** [comment]
Thanks for the fast answer. I'll check out the FileVersion object!

As for the second answer. Your suggestions sounds good to me. The files I'm handling range from 0,1mb to 50mb usually. Do you happen to have an example? I am somewhat of a python noob and the whole scripting nature of it makes it more difficult

**Comment by ppolewicz** [comment]
If it's 50MB then I think you can buffer it in memory with no problem, see [b2sdk.v1.Bucket.upload_bytes()](https://b2-sdk-python.readthedocs.io/en/master/api/bucket.html#b2sdk.v1.Bucket.upload_bytes) for the method to actually do it

**Comment by SerdaOzun** [comment]
Thanks a lot. Everything is working perfectly fine now :). authorize_account is indeed returning FileVersion btw, hence I needed to use .id_ and not .id 
Probably worth adding it to the documentation as the return type.
 Really liking this api. Issue can be closed.

**Comment by ppolewicz** [comment]
@SerdaOzun would you like to do the honors of adding the return type to the documentation? I don't want to steal credit for your contribution :)

**Comment by SerdaOzun** [comment]
done 😉 https://github.com/Backblaze/b2-sdk-python/pull/152
