### ISSUE TITLE
Specifying folder when using upload_local_file()

### ISSUE THREAD

**Issue by EMplIFil** [Backblaze/b2-sdk-python#171]
Hi there,

Is there functionality to upload a file to a folder when using the upload_local_file() function?

Example: "my_folder/my_file.txt"

I assumed that it would be possible simply by prepending the B2 folder path to the file_name argument. However, this didn't work (no file appears although the function doesn't throw any errors).

I've confirmed that uploading a file without any folder (e.g. "my_file.txt") does work.

What is the correct way to upload a file to a specific folder?

Just to be clear, the folder does exist.

**Comment by ppolewicz** [comment]
I suspect you are uploading the file correctly, but then when you are listing the contents of the bucket, you are not using `--recursive` flag for CLI's `ls` subcommand and that hides the file in the folder from output. Please inspect the folder with `b2 ls --recursive` or via web interface.

**Comment by EMplIFil** [comment]
I see it now and have verified there are no errors in the file.

Yesterday, I was using the web interface and refreshed several times over the course of an hour or so but didn't see it. I suppose it is an issue with the web interface then or maybe there is some delay?

Thanks!

**Comment by ppolewicz** [comment]
I'm happy to hear that it's working fine for you :)

I can't speak on the caching of the web interface - I honestly have no idea how it works. I personally think it should not be caching anything. Maybe you've hit some other issue (bad caching proxy, browser-side issue or something). If you want to investigate that angle further, I'm afraid you need to email b2 support team.

It is difficult to find and talk to users of b2sdk, so since I have you here, I'd like to ask you (if you don't mind sharing) what for and how do you plan to use b2sdk. This information would allow me to plan future development of b2sdk and b2cli better.

**Comment by EMplIFil** [comment]
Appreciate the interest.

I have a very simple use case and my strategy has been to just hack my way along on an as-needed basis.

Currently I have a script that creates daily backups of the database for my webapp. After dumping the backup file, I upload the result to B2.

I chose Python only because I use Python for nearly everything, so the cognitive load is less.

**Comment by ppolewicz** [comment]
what format is the backup in? How large is the file? Does the database stay the same mostly or does it change a lot?

**Comment by EMplIFil** [comment]
It is a .sql file (plain text). Only ~20MB. Does not change very much.

**Comment by ppolewicz** [comment]
All right, thanks. I think you could just use `b2 sync` from b2cli - it would be easier than writing the retention policies etc in python (3 lines to install + one line to run it, but `bash`, not python).
