### ISSUE TITLE
Documentation is not for latest release, but for develop branch

### ISSUE THREAD

**Issue by AntonLydike** [Backblaze/b2-sdk-python#176]
I was looking at ways to get a file id by it's name, and found `get_file_info_by_name` in the documentation [here](https://b2-sdk-python.readthedocs.io/en/master/api/bucket.html#b2sdk.v1.Bucket.get_file_info_by_name)

Sadly this feature is not available in the latest 1.2.0 release. This begs the question why the documentation differs from the released package. And also when the new features will be released, as I cannot find a way to get a file id from a name without listing all files.

**Comment by ppolewicz** [comment]
@mlech-reef could you please take a look at the docs generation?

As for `bucket.get_file_info_by_name` and `bucket.get_file_info_by_id`, I've triggered a discussion about releases so that we maybe do them more often, but for now please use the development version. I'm not sure if we should do a release next week, if something blows up it will be hard to scramble people to investigate and fix things.

**Comment by mlech-reef** [comment]
As by the convention, the `latest` branch of the documentation should point to the development branch which is `master` in our case:
https://docs.readthedocs.io/en/stable/versions.html#how-we-envision-versions-working
The version is visible and can be changed on the left panel.

The new version of the SDK is going to be released this week.

**Comment by mlech-reef** [comment]
B2 SDK 1.3.0 has been released. I'm closing this issue.
