### ISSUE TITLE
Change ScanPoliciesManager interface (see TODOs)

### ISSUE THREAD

**Issue by mlech-reef** [Backblaze/b2-sdk-python#196]
`ScanPoliciesManager.should_exclude_file` should accept `File` object, not string
`ScanPoliciesManager.should_exclude_directory` should accept `AbstractFolder` object, not string

**Comment by mpnowacki-reef** [comment]
@mlech-reef Why is this needed for V2?

**Comment by mlech-reef** [comment]
It breaks compatibility.

**Comment by mpnowacki-reef** [comment]
@ppolewicz In light of 

> change all path arguments everywhere (internally too) to use pathlib instead of strings

from https://github.com/Backblaze/b2-sdk-python/issues/139

should `should_exclude_file` and `should_exclude_directory ` indeed use `File` and `Folder` and not `pathlib.Path` ?

**Comment by ppolewicz** [comment]
I think the problem here is that `should_exclude_file` and `should_exclude_directory` can have b2:// `File` / `Folder` passed into them and `pathlib.Path` doesn't support b2:// resources

**Comment by mpnowacki-reef** [comment]
The way `ScanPoliciesManager.should_exclude_file` and `ScanPoliciesManager.should_exclude_directory` work right now is they compare B2 paths to sets of regexes - even though it's not documented, they never operate on local paths. Even when invoked in LocalFolder, a would-be-B2-path of a dir or a file is constructed and passed to the appropriate ``ScanPoliciesManager.should_exclude_*` method. I'm not sure it would be beneficial to create "possibly-existsing-b2-file" objects when scanning local folders just to match their paths against regexes.

@mlech-reef Is this interface change somehow needed elsewhere? Or do you need access to all B2File versions (carried by B2File) in your implementation of `ScanPoliciesManager` ?

**Comment by mpnowacki-reef** [comment]
However, changing the interface to have the following methods:

 * `should_exclude_local_file` accepting a `LocalFile` object
 * `should_exclude_b2_file` accepting a `B2File` object
 * `should_exclude_local_folder` accepting a `LocalFolder` object
 * `should_exclude_b2_floder` accepting a `B2Folder` object
 
 and performing the translations internally would make for a clean, extensible API. The problem is that `ScanPoliciesManager` objects would need access to `local_dir` and `b2_dir` to perform translations accurately. Or maybe a subdelegate of `ScanPoliciesManager`, a policy manager aware of the particular sync context?

**Comment by mlech-reef** [comment]
@mpnowacki-reef The TODO was created just to not operate on str-like object carrying paths. Just for that.
