### ISSUE TITLE
Synchronizer didn't resume interrupted large file upload

### ISSUE THREAD

**Issue by dlime** [Backblaze/b2-sdk-python#304]
I'm using `Synchronizer` to upload a 20GB file from source to a B2 bucket.

I've hit Ctrl+C while `Synchronizer.sync_folders()` was at about 10%.

The interrupted file is shown in the bucket as `filename (started large file)`

However when re-running the upload code I was expecting the upload to start again at around 10% but instead starts again at 0%.

Is this expected?

Extra info:
* B2 sdk version: 1.14.0
* The code I'm using is essentially the same as the quick start guide: https://b2-sdk-python.readthedocs.io/en/master/quick_start.html#synchronization)
* `compare_threshold` and `compare_version_mode` are left with default values

**Comment by ppolewicz** [comment]
Large file upload splits the file into parts - if none of them have completed the upload, then the retry will be from 0%. You can reduce the number of threads or the part size to improve the continuation but then your performance may not be as good.

It could be a bug, but it looks like expected behavior. If you would be running your code with logs and you could show those logs, then log review could tell us what actually happened. So far I think it's expected behavior.

**Comment by dlime** [comment]
I tried again, interrupted at around 60% (to be safe that chunks were uploaded by threads) and indeed the upload resumed at 60% on the next attempt.

Thank you also for the explanation of how resume works, since couldn't find info about in Synchronizer documentation.
