### ISSUE TITLE
Add b2_get_upload_url support

### ISSUE THREAD

**Issue by DavBE** [Backblaze/b2-sdk-python#382]
Hello,

According to https://www.backblaze.com/b2/docs/b2_get_upload_url.html, the API supports a b2_get_upload_url operation.

I would love it to be available in the SDK. Could  that be implemented ?

Best regards,

David

**Comment by ppolewicz** [comment]
It's already available in the sdk in the Session class, but this is a very low-level construct. How would you use it directly?

**Comment by DavBE** [comment]
Use case : I am delegating jobs to celery workers distributed on remote machines. I want these workers to upload some files to a b2 bucket but I don't want them to need/know any credentials.

I would like to be able to do something like : 

```python
info = InMemoryAccountInfo()
b2_api = B2Api(info)
b2_api.authorize_account("production", app_key_id, app_key)
bucket = b2_api.get_bucket_by_name(bucket_name)
url, token = bucket.get_upload_url()
```

Does that make sense ?

**Comment by ppolewicz** [comment]
As per documentation
> An uploadUrl and upload authorizationToken are valid for 24 hours or until the endpoint rejects an upload

If for some reason the endpoint does reject an upload (usually something silly like "this server is full now, go get a new token for a new server that is not full") then celery, not having a key, won't be able to renegotiate a token and the task will fail.

I think the celery worker should just have a key with `writeFiles`, right?

**Comment by DavBE** [comment]
> If for some reason the endpoint does reject an upload (usually something silly like "this server is full now, go get a new token for a new server that is not full") then celery, not having a key, won't be able to renegotiate a token and the task will fail.

My plan was to generate a bunch of authorizations and pass them to the worker so it could retry if the upload fails. Now if the upload still fails after many attempts, the task will fail indeed but so be it.

> I think the celery worker should just have a key with writeFiles, right?

The whole point is to prevent the worker to have a key. I think this serves many purposes and have benefits :
- no need to manage keys
- security : if worker is compromised, the bucket is safe

Now, having re-read the documentation, I see why it is a low level api call. I can call the API and generate the urls without using the B2 SDK, I just thought it would have been a nice addition.

**Comment by ppolewicz** [comment]
If the worker is compromised, but holds a temporary upload url, it effectively has the same access as if it had a `writeFiles`-capable key, however:
- it cannot renegotiate an url if something happens to it (and depending on the cluster health, you might get a series of keys that will expire at the same time). As servers get filled up with data, Backblaze adds more servers and (I think) those need new keys, also a big cluster has more "resiliency groups" than a small one so YMMV
- it cannot be revoked separately from the main key that the application uses
- this gets progressively worse as the object size goes up and speed goes down - the longer the upload part urls live, the higher the chance is that they will need to be regenerated. If you have very big objects that you upload slowly (due to latency for example, from Asia or Australia) then you'll have a higher failure rate than if you upload a small object 2ms away from the datacenter. This is normally handled on the client side.

I don't think the system was designed in the way in which you are trying to use it... That being said, I think it'll work, especially when you are ok with the task failing sometimes (I assume you retry it on a higher level).

b2-sdk-python has not been designed in a way in which it is easy for the caller to upload files without a key, so it'll need a little bit of trickery (maybe 8 LOC?) however I think you will still benefit greatly from using the sdk rather than calling the API directly. On the server side, generation of the url will be easier if you can call it from Session - then you don't need to worry about the expiring auth tokens, retries work out of the box, 429 backoff is handled for you, in case of trouble you get a nice exception, there are logs that will show you what happened if you ever get in trouble etc. Of course you can handle it all by yourself in your code - I'm just saying that you could also import this functionality from b2-sdk-python. It's natively supported, you just need to call `b2_api.session.get_upload_url(bucket.id_)`

On the worker side you'd have to initialize an account info object (`InMemoryAccountInfo` is kind of made for this) with fake data and put upload urls into it by calling `account_info.put_bucket_upload_url(bucket.id_, upload_url, upload_auth_token)`. Then you should be able to use `Bucket.upload()`.

**Comment by DavBE** [comment]
Thank you for the comprehensive explanation. I guess I can close the ticket.
