### ISSUE TITLE
b2sdk.v2.SqliteAccountInfo does not raise an error when it fails to locate an account file

### ISSUE THREAD

**Issue by titus8** [Backblaze/b2-sdk-python#457]
When `b2sdk.v2.SqliteAccountInfo` fails to locate an account file, it does not raise an error, and it creates the file "None" in the current working directory, which naturally contains no credentials. As a result, `b2sdk.v2.B2Folder` fails loudly later on.

A partial application workaround is to check the `b2sdk.v2.SqliteAccountInfo` instance variable `filename` for the value `"None"` immediately after calling `b2sdk.v2.SqliteAccountInfo`. However, "None" has already been created.

`b2sdk.v2.SqliteAccountInfo` should raise an error when it fails to locate a file, and it should not create the file "None".

**Comment by vbaltrusaitis-reef** [comment]
Could you share the following:
1. `b2sdk` version you are using
2. operating system you are using
3. `filename` and `profile` parameters you're using to create `b2sdk.v2.SqliteAccountInfo`
4. what (if any) `B2_ACCOUNT_INFO` environment variable is set

**Comment by ppolewicz** [comment]
I think in such case the app wouldn't just need the file to exist, but it'd expect the `SQliteAccountInfo` to be already configured with an `authorize_account` call, right? Would an empty (not fully authorized due to a bug / unexpected hardware restart or after `clear_account()` was ran) `SQliteAccountInfo` be useful?

I think if you need to know if it's fresh or good, you might need to query the SQliteAccountInfo object to determine its state and then decide how to proceed in the logic of your application.
