### ISSUE TITLE
Error: externally-managed-environment on Ubuntu 24.04

### ISSUE THREAD

**Issue by adrianbienias** [Backblaze/b2-sdk-python#507]
When trying to install sdk via
```bash
pip install b2sdk
```

the following error appears in the console
```bash
Error: externally-managed-environment
```

In the error's body, there's a suggestion to use `pipx`.

But after successful installation via

```bash
pipx install b2sdk --include-deps
```

the following error still appears (when trying to perform backup via duplicity):

```
BackendException: B2 backend requires B2 Python SDK (pip install b2sdk)
```

Any ideas how to solve it?

**Comment by mjurbanski-reef** [comment]
This is a common error for Ubuntu and other Linux distros as well as MacOS, due how they handle `pip` package manger.

https://askubuntu.com/a/1469197 contains a rather comprehensive answer, to which I would only add that `pipx` is for applications and not libraries (such as b2sdk) as by design it installs everything in isolation, so for example, `duplicity` has no access to it.

My recommendations would be to either:
A) Use create a dedicated venv and install  both `b2sdk` and `duplicity` within it. Safest option, but requires understading how to use python virtualenvs.
B) Force installation system(/user)-wide using `pip install b2sdk --break-system-packages`
C) Install outdated `b2sdk` package using `apt`, which will likely work but will not contain latest fixes

**Comment by ppolewicz** [comment]
You can also use the linux binary release or docker

**Comment by mjurbanski-reef** [comment]
Duplicity uses b2sdk directly, so using `b2` CLI binary/docker is not possible.

**Comment by adrianbienias** [comment]
I see. Thanks @mjurbanski-reef for the explanation!
