### ISSUE TITLE
arrow dependency

### ISSUE THREAD

**Issue by 2x2xplz** [Backblaze/b2-sdk-python#63]
the `requirements.txt` lists `arrow>=0.8.0,<0.13.1`

arrow is currently at 0.14.2 and therefore causes issues/warnings in `pip`

I reviewed the code, it's just a few lines of very basic usage which doesn't appear to have any issues with later versions. Please update the `requirements.txt` file.

**Comment by ppolewicz** [comment]
Arrow 0.14.2 does not support Python 3.4, which we still do support. I'll try to figure something out.

**Comment by RainbowHackerHorse** [comment]
Howdy @ppolewicz 
It seems like you fixed the issue in PR #64 
Can we get this merged in? b2 has been broken on my FreeBSD system for months due to this. Manual fixes are working okay for now, but every `pkg upgrade` overwrites the requirements.txt file. I'd rather get this resolved here upstream than open a FreeBSD specific patch.
Thanks!
