### ISSUE TITLE
Problem Creating Key

### ISSUE THREAD

**Issue by dustydingo** [Backblaze/b2-sdk-python#98]
Not exactly related to the SDK. However, I am trying to access B2 using Python with the `requests` library to create a new key. My code is as below:

```python
import requests
 
response = request.get("https://api.backblazeb2.com/b2api/v2/b2_create_key", params={'accountId': 'xxxx', 'capabilities': ['listKeys','listBuckets','listFiles','readFiles','shareFiles','writeFiles','deleteFiles'], 'keyName': 'test'}, headers={'Authorization': 'xxxx'})
```

I have included the values for the account ID and the authorization. I am able to access other B2 services. However, when using the above function I get the following error:

```python
{'code': 'bad_request', 'message': 'duplicate name in query string: capabilities', 'status': 400}
```

Any idea how to overcome this?

**Comment by ppolewicz** [comment]
You are passing the list of capabilities incorrectly, causing parameter name duplication and server rejects it.

I'm curious. Why are you using requests and not b2sdk?

**Comment by dustydingo** [comment]
How should they be passed? I have tried passing them as a string `listKeys,writeFiles` or something like this `"'listKeys','writeFiles'"`. However, neither seem to work.

Also, I was just curious trying to re-create the B2 API based on the documentation provided at the B2 website.

**Comment by ppolewicz** [comment]
Please refer to b2sdk/raw_api.py and b2sdk/b2http.py

From the perspective of python developer community it would be great if you would contribute to the b2cli or b2sdk repository to make it even better, rather than recreating it. We've been working on it in a group of quite a few people for many years now, your implementation is unlikely to catch up any time soon. We have unit tests, CI, documentation, cloud simulator for easy application testing and other fancy stuff. Maybe you'd like to join the project, fix a small easy bug for a start to get your feet wet?

**Comment by dustydingo** [comment]
I think that is a great idea! I definitely will if I find any bug or what not.


Right now I have been working on this for some time, just out of curiosity for the B2 API. I'm still not able to find out how to go about this but thanks for taking the time to direct me in the right direction.
